### PR TITLE
Bugfix/sigil speed calculation

### PR DESCRIPTION
**Pull request by Zoma-Ancestral**

### CODE REVIEW

**Review by Sludging — CHANGES_REQUESTED** [review]
I'm trying to avoid re-using the same function in the post-processing and post-post-processing (I still hate it) maps.

Can you pull out the whole "calculate sigil speed" math out to it's own function and call that in the post-post-processing map? 

Essentially splitting out the calculation to something that only matters for the UI and doesn't effect other calculations (unlike the artifact piece which does, hence why it needs to remain in the post processing step)

**Comment by Zoma-Ancestral** [comment]
> I'm trying to avoid re-using the same function in the post-processing and post-post-processing (I still hate it) maps.
> 
> Can you pull out the whole "calculate sigil speed" math out to it's own function and call that in the post-post-processing map?
> 
> Essentially splitting out the calculation to something that only matters for the UI and doesn't effect other calculations (unlike the artifact piece which does, hence why it needs to remain in the post processing step)

Sure I understand, gonna edit that

**Comment by Zoma-Ancestral** [comment]
I Simply splitted the updateSigils, could've completely done the speed calculation into Alchemy page when rendering but I guess it wouldn't be very clean (that would mean nothing in post post processing, so if you'd prefer it that way tell me)

**Review by Sludging — APPROVED** [review]

**Comment by Sludging** [comment]
> I Simply splitted the updateSigils, could've completely done the speed calculation into Alchemy page when rendering but I guess it wouldn't be very clean (that would mean nothing in post post processing, so if you'd prefer it that way tell me)

This is my preferred way. I may be wrong on how re-rendering and UI works but I feel like doing this math once during cloud save load vs doing it literally every time the page renders feels much more efficient.

**Pull request merged**
